version: 2.1

orbs:
    node: circleci/node@3.0.1

jobs:
    build-and-test:
        docker:
            - image: cimg/node:12.16
        resource_class: small
        steps:
            - checkout
            - node/install-packages:
                pkg-manager: yarn      
            - run:
                name: Test application
                command: |
                    TEST=$(circleci tests glob "src/__tests__/*.js") 
                    yarn test $TEST          
workflows:
    build-and-test:
      jobs:
        - build-and-test